# -*- coding: utf-8 -*-
"""Presentacion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kv04GmoiEnGVrF7nOKMgWzNpRcpJGAjF

#Presentacion

##El uso de print en python

Print es una funcion que permite la salida en pantalla de lo que nosotros queremos, puede ser desde el valor de una variable o el valor de varia variables a la vez escribiéndolas entre comas como en el siguiente ejemplo:
"""

A = 4
B = 'PABLO'
A
A, B

"""###La función print nos permite incluir variables o expresiones como argumentos, lo que nos permite combinar texto y variables por ejemplo:"""

Nombre = 'Pablo'
Edad = 19
print ('Me llamo', Nombre , 'Y tengo ', Edad, 'años')